// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbin4ldDgDcVx1ki6MOxChycHAbSBCIvk',
    appId: '1:21497506057:web:e1b2fd3cf114f4c95fcbd8',
    messagingSenderId: '21497506057',
    projectId: 'videoapp-2f991',
    authDomain: 'videoapp-2f991.firebaseapp.com',
    storageBucket: 'videoapp-2f991.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLJyZVsyE8R6zGcZlOh8eD1ThqU9V_x9I',
    appId: '1:21497506057:android:d2ab98968a02a6975fcbd8',
    messagingSenderId: '21497506057',
    projectId: 'videoapp-2f991',
    storageBucket: 'videoapp-2f991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSF6qQzzbU0VURFpeg4wwq6WB0nWQq4Kc',
    appId: '1:21497506057:ios:5017f666719c8e475fcbd8',
    messagingSenderId: '21497506057',
    projectId: 'videoapp-2f991',
    storageBucket: 'videoapp-2f991.appspot.com',
    iosClientId: '21497506057-5klbg3n2m9gg40s5d55eo1m9vr28s2pa.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSF6qQzzbU0VURFpeg4wwq6WB0nWQq4Kc',
    appId: '1:21497506057:ios:5017f666719c8e475fcbd8',
    messagingSenderId: '21497506057',
    projectId: 'videoapp-2f991',
    storageBucket: 'videoapp-2f991.appspot.com',
    iosClientId: '21497506057-5klbg3n2m9gg40s5d55eo1m9vr28s2pa.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoApp',
  );
}
